import React from 'react';

const TerminosYPoliticas = () => {
    return (
        <section id="section_formulario" style={{ marginTop: "10px", width: "100%", paddingBottom: "50px" }}>

            <div style={{ width: "700px", margin: "0 auto" }}>
                <h1>Términos y Políticas de Uso</h1>
                <h3 className="center">Sistema Check (DSL Solutions)</h3>
                <p><span style={{ fontWeight: "400" }}>Bienvenido al Sistema Check, un sistema de gestión de datos diseñado por DSL Solutions Inc. habilitado principalmente para &nbsp;guardar y manejar información de clientes, transacciones y servicios en línea de los negocios participantes en este grupo;</span></p>
                <p><em><span style={{ fontWeight: "400" }}>Para efectos de este acuerdo, a partir de este momento , &nbsp;“Sistema Check” &nbsp;será mencionado como “Check” o “Sistema” y el contratante del servicio será mencionado como “El usuario”.</span></em></p>
                <p><span style={{ fontWeight: "400" }}>Antes de iniciar su &nbsp;cuenta de Check, </span><em><span style={{ fontWeight: "400" }}>El usuario </span></em><span style={{ fontWeight: "400" }}>debe leer y estar de acuerdo con los términos de uso. Todas las políticas y términos de trabajo para usar el sistema Check están establecidos en este acuerdo. Al usar o establecer una cuenta de Check, usted (“El usuario”) acepta los acuerdos y políticas establecidas en el presente convenio.</span></p>
                <p><span style={{ fontWeight: "400" }}>Estos Términos de servicio comprenden un acuerdo legal entre usted y DSL Solutions Inc. Por favor revise este acuerdo cuidadosamente .</span></p>
                <p><span style={{ fontWeight: "400" }}> Al suscribirse o crear una cuenta de acceso a Check usted acepta que las partes involucradas estarán sujetas por estas condiciones de servicio , y ambas partes reconocen que han leído, entendido y aceptado el acuerdo por los siguientes términos y condiciones, incluyendo las directrices adicionales y modificaciones futuras ( para este acuerdo llamadas, los "Acuerdos") .</span><em><span style={{ fontWeight: "400" }}> El &nbsp;presionar el botón "Ingresar " se considera equivalente a &nbsp;la firma de un acuerdo de trabajo en papel. Por favor si no está de acuerdo con los términos y políticas del servicio, no debe hacer clic en este botón.</span></em></p>
                <ol>
                    <li><strong> El servicio del Sistema Check.</strong></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>El sistema ChecK es una plataforma (Software, Hardware) para la gestión &nbsp;de información de empresas con necesidades específicas para el manejo de dichos datos. </span><a href="http://www.dslsistemacheck.com"><span style={{ fontWeight: "400" }}>&nbsp;</span><span style={{ fontWeight: "400" }}>www.dslsistemacheck.com</span></a><span style={{ fontWeight: "400" }}> permite al </span><em><span style={{ fontWeight: "400" }}>usuario </span></em><span style={{ fontWeight: "400" }}>el acceso al desarrollo el cual es propiedad de DSL Solutions, Inc. y ofrece un software &nbsp;para crear, gestionar, </span><em><span style={{ fontWeight: "400" }}>guardar en &nbsp;un servidor o nube</span></em><span style={{ fontWeight: "400" }}>, transmitir, compartir, distribuir, &nbsp;imprimir, entre otras la información que para su uso sea necesaria e indispensable (lo que en lo suscesivo se llamará “Contenido”). El uso del mismo contenido es bajo su propio riesgo y responsabilidad ya que el sistema Check está diseñado principalmente para facilitar su gestión. Todo el contenido que sea ingresado al sistema es propiedad de </span><em><span style={{ fontWeight: "400" }}>usted y de su empresa, al igual que las responsabilidades legales por su uso.</span></em></p>
                <ol start="2">
                    <li><strong> Privacidad</strong></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>La privacidad de usted, su negocio y sus clientes es importante para DSL Solutions, Inc; Por ello en nuestra &nbsp;política de privacidad usted puede encontrar todos los términos a los que hacemos referencia. Por favor lea cuidadosamente la política de privacidad para obtener información relativa al uso, divulgación y recolección que &nbsp;DSL Solutions Inc. hace de su información personal.</span></p>
                <ol start="3">
                    <li><strong> Modificación de estos términos</strong></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>Cualquier información adicional sobre los cambios de términos o políticas de uso serán publicados en el sistema Check,</span><em><span style={{ fontWeight: "400" }}>al igual que cualquier información que sea agregada o corregida, </span></em><span style={{ fontWeight: "400" }}>lo cual permitirá a todos los usuarios de este sistema conocer tal información.</span><em><span style={{ fontWeight: "400" }}> Los cambios serán mostrados</span></em><span style={{ fontWeight: "400" }}> en el mismo sistema o enviados vía correo para su conocimiento y aprobación. Todas estas directrices y reglas se encontrarán incorporadas a este acuerdo de Términos de Servicio.</span></p>
                <p><span style={{ fontWeight: "400" }}>DSL Solutions Inc., puede, a su discreción, modificar o revisar estos “Acuerdos” de servicio en cualquier momento; Al utilizar el “Servicio”, usted acepta dichos acuerdos con estas modificaciones o revisiones. Si no acepta el acuerdo le pedimos que no use el servicio.</span></p>
                <ol start="4">
                    <li><strong> Uso del servicio</strong></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>Usted es responsable</span><em><span style={{ fontWeight: "400" }}> de la seguridad y uso de sus propias comunicaciones y transmisiones desde su cuenta a través el servicio,</span></em><span style={{ fontWeight: "400" }}> y por todo el “Contenido” enviado y almacenado hacia y desde su cuenta, así también como de la actividad que ocurra bajo su misma administración </span><em><span style={{ fontWeight: "400" }}>(incluso del contenido publicado o editado por otros que tienen acceso con su cuenta)</span></em><span style={{ fontWeight: "400" }}> y de las consecuencias derivadas o derivadas de las mismas. El usuario deberá utilizar el “Servicio” de acuerdo con las regulaciones locales, las leyes estatales , nacionales e internacionales , así como también las normas y reglamentos donde sea aplicable, incluyendo aquellas leyes relativas a la transmisión de datos desde el país en que &nbsp;resida o ejecute el sistema.</span><em><span style={{ fontWeight: "400" }}>Si tiene usted dudas respecto a este acuerdo, le sugerimos consulte a un profesional en estas areas.</span></em></p>
                <p><strong><em>El usuario </em></strong><strong>no debe, aceptar, autorizar o </strong><strong><em>solicitar</em></strong><strong> &nbsp;a terceros a: </strong></p>
                <ol style={{ listStyleType: "lower-alpha" }}>
                    <li><span style={{ fontWeight: "400" }}>Utilizar el “Servicio” para cargar, almacenar, transmitir o distribuir cualquier contenido que sea ilegal, difamatorio, abusivo, fraudulento, obsceno, que contenga virus o sea censurable según lo determine razonablemente las autoridades competentes; </span></li>
                    <li><span style={{ fontWeight: "400" }}>Cargar, almacenar, transmitir o distribuir contenido que infrinja los derechos de propiedad intelectual de terceros u otros derechos y/o obligaciones de propiedad, contractuales o beneficiarias; </span></li>
                    <li><span style={{ fontWeight: "400" }}>Permitir que otras personas que utilizan el “Servicio” bajo su cuenta lo hagan con fines fraudulentos o inapropiados. </span></li>
                    <li><em><span style={{ fontWeight: "400" }}>Compartir con personas u organizaciones no autorizadas por el usuario la información contenida en CHECK.</span></em></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>La violación de cualquiera de los párrafos anteriores puede resultar en la terminación inmediata de este “Acuerdo” y su cuenta, y puede suponerle s</span><em><span style={{ fontWeight: "400" }}>anciones locales,</span></em><span style={{ fontWeight: "400" }}> estatales y/o federales entre otras consecuencias legales. DSL Solutions, Inc. se reserva el derecho, pero no tendrá ninguna obligación, de investigar su uso del servicio con el fin de determinar si existe o se ha producido una violación del “Acuerdo”, o para cumplir con cualquier ley, regulación, proceso legal o solicitud gubernamental.</span></p>
                <ol start="5">
                    <li><strong> Contenido del Servicio, propiedad y derechos de propiedad intelectual.</strong></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>DSL Solutions, Inc., no asume ninguna responsabilidad por el contenido</span><em><span style={{ fontWeight: "400" }}> que el usuario, sus empleados o cualquier persona a la que el usuario le conceda acceso al sistema, terceros </span></em><span style={{ fontWeight: "400" }}>(incluyendo, y no limitado, cualquier tipo de virus u otros elementos perjudiciales), tampoco asume la obligación de controlar dichos contenidos de terceros. DSL Solutions Inc., se reserva el derecho en cualquier momento de suprimir o rechazar la distribución de cualquier contenido en el “Servicio”, como contenidos que infrinjan las condiciones de este “Acuerdo”. DSL Solutions, Inc. también se reserva el derecho de acceder, leer, preservar y revelar cualquier tipo de información y contenido, si considera &nbsp;es necesaria para: &nbsp;</span></p>
                <p><span style={{ fontWeight: "400" }}>(A) cumplir con leyes, regulaciones, procesos legales,</span><em><span style={{ fontWeight: "400" }}> a solicitud de las autoridades competentes </span></em></p>
                <p><span style={{ fontWeight: "400" }}>(B) hacer cumplir este “Acuerdo”, incluyendo la investigación </span><em><span style={{ fontWeight: "400" }}>de violaciones potenciales del mismo acuerdo </span></em></p>
                <p><span style={{ fontWeight: "400" }}>(C) detectar, prevenir, o de cualquier m</span><em><span style={{ fontWeight: "400" }}>odo abordar contenidos fraudulentos o ilegales,</span></em><span style={{ fontWeight: "400" }}> fraude, seguridad o temas técnicos (incluyendo, y no limitado, el filtrado de correo no deseado), </span></p>
                <p><span style={{ fontWeight: "400" }}>(D) responder a solicitudes de asistencia de los usuarios. </span></p>
                <p><span style={{ fontWeight: "400" }}>(E) proteger los derechos, propiedad o seguridad de DSL Solutions, </span><em><span style={{ fontWeight: "400" }}>sus asociados y empleados Inc., sus usuarios y el público. </span></em></p>
                <p><span style={{ fontWeight: "400" }}>DSL Solutions, Inc. no será responsable del ejercicio o no ejercicio de sus derechos en virtud del presente “Acuerdo”.</span></p>
                <p><span style={{ fontWeight: "400" }}>Las interfaces visuales , gráficos, diseños , recopilación , información, código de computadora (incluyendo el código fuente o código objeto), los productos , los servicios , y todos los demás elementos o módulos de acceso &nbsp;al sistema que son proporcionadas al usuario son &nbsp;propiedad de DSL Solutions, Inc., y están protegidos por los derechos de autor en Estados Unidos y México; La imagen de marca , las patentes y derechos de autor de las marcas registradas , los convenios internacionales , y cualquier otra propiedad intelectual pertinente y de derechos de propiedad con las leyes aplicables &nbsp;son propiedad de DSL Solutions, Inc. o sus subsidiarias o compañías afiliadas y/o terceros licenciatarios. Salvo que se indique lo contrario, todas las marcas registradas , marcas de servicio y nombres comerciales son propiedad de DSL Solutions Inc. , licenciatarios, o sus filiales y/o de terceros.</span><span style={{ fontWeight: "400" }}><br /></span><span style={{ fontWeight: "400" }}>DSL Solutions, Inc. no reclama la titularidad de ninguno de los contenidos , incluyendo textos , datos, información , imágenes , fotografías , música, sonido , vídeo ,</span><em><span style={{ fontWeight: "400" }}> u otro material , que sean ingresados, &nbsp;transmitidos o almacenados &nbsp;en el “Sistema”.</span></em></p>
                <ol start="6">
                    <li><strong> Declaraciones de usuario y garantías.</strong></li>
                </ol>
                <p><em><span style={{ fontWeight: "400" }}>El usuario &nbsp;es el único responsable de ingresar contenidos al sistema Check, también de almacenar, transmitir o distribuir dicho contenido para su conveniencia, así como también el de sus cuentas abiertas para su empresa o sucursal, con lo cual el usuario asume el compromiso y responsabilidad pro la veracidad y buen uso de dichos contenidos . Tal y como &nbsp;se establece en el presente documento, DSL Solutions, Inc., no utilizará dicho contenido para ningún propósito excepto para ofrecerle el servicio y realizar mejoras en la medida que se requiera, y/o cumplir los mandatos legales de las autoridades.</span></em><em><span style={{ fontWeight: "400" }}><br /></span></em><span style={{ fontWeight: "400" }}><br /></span><span style={{ fontWeight: "400" }}>A. Al cargar, almacenar, transmitir o distribuir &nbsp;cualquier contenido, usted afirma, declara y garantiza que:</span> <span style={{ fontWeight: "400" }}>A) el contenido y uso de él no lo hace y no podrá: </span></p>
                <ol>
                    <li><span style={{ fontWeight: "400" }}>Infringir, violar o apropiarse indebidamente de cualquier derecho de terceros, incluyendo los derechos de autor, marca registrada, patente, secreto comercial, derecho moral, derecho de privacidad, derecho de publicidad o cualquier otra propiedad intelectual o derecho de propiedad, </span></li>
                    <li><span style={{ fontWeight: "400" }}>Violar ninguna ley o regulación de valores en cualquier jurisdicción. </span></li>
                    <li><span style={{ fontWeight: "400" }}>Calumniar o difamar a cualquier otra persona.</span></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>B. El contenido no contenga ningún virus, adware, spyware, gusanos, u otros códigos maliciosos.</span><span style={{ fontWeight: "400" }}><br /></span><span style={{ fontWeight: "400" }}>Los infractores de cualquier derecho de terceros pueden estar sujetos a responsabilidad penal y civil. DSL Solutions, Inc. se reserva todos los derechos y recursos contra los usuarios que violen estos”Acuerdos” de servicio.</span></p>
                <ol start="7">
                    <li><strong> Contenido del aviso legal</strong></li>
                </ol>
                <p><em><span style={{ fontWeight: "400" }}>El usuario acepta</span></em><span style={{ fontWeight: "400" }}> &nbsp;que al utilizar y acceder al &nbsp;sistema &nbsp;puede estar expuesto a contenido de una variedad de fuentes, y que &nbsp;DSL Solutions , Inc. no es responsable de la exactitud , utilidad , o de los derechos de propiedad intelectual de o en relación a dichos fuentes o “Contenido” . </span><em><span style={{ fontWeight: "400" }}>El usuario acepta &nbsp;que al utilizar el sistema podría estar expuesto a </span></em><span style={{ fontWeight: "400" }}>“Contenido” que es inexacto, ofensivo, indecente u objetable , y usted está de acuerdo en &nbsp;renunciar a cualquier derecho o recurso legal o equitativo que tenga o pueda tener en contra de &nbsp;DSL Solutions , Inc . con respecto a la misma fuente o “Contenido” . DSL Solutions, Inc. no patrocina ningún contenido ni ninguna opinión , recomendación o consejo expresado en ella, y también renuncia expresamente a cualquier &nbsp;responsabilidad en relación con el “Contenido” y sus fuentes, aunque estas mismas sean de otras cuentas del mismo “Sistema” .</span></p>
                <ol start="8">
                    <li><strong>Declaración de las Políticas</strong></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>DSL Solutions , Inc. renuncia a cualquier &nbsp;responsabilidad en relación al “Contenido” subido , almacenado , transmitido o distribuido de alguna forma por el “Usuario”. En el caso de que DSL Solutions, Inc. reciba información o aviso de que cualquier “Contenido” subido , almacenado , transmitido o distribuido por un usuario, y que &nbsp;éste violara este “Acuerdo” de servicio o infrinja cualquier derecho de autor , marca registrada , o de la patente , o se alegue que infringe algun derecho de autor , marca registrada o patente, DSL Solutions,Inc. se reserva el derecho de eliminar inmediatamente el “Contenido” sin previo aviso al usuario y sin ningún tipo de obligación de investigar la denuncia o infracción. DSL Solutions, Inc. se reserva el derecho, a su discreción única para eliminar por cualquier razón cualquier &nbsp;tipo y en cualquier momento, el contenido subido , almacenado , transmitido o distribuido de otro modo por un usuario , sin previo aviso tanto para él como para otros usuarios del “Sistema”.</span><span style={{ fontWeight: "400" }}><br /></span><span style={{ fontWeight: "400" }}>DSL Solutions, Inc. se reserva el derecho de suspender el acceso del usuario a la página web y al &nbsp;sistema en el caso de que el usuario &nbsp;viole estos &nbsp;“Acuerdos” de servicio .</span></p>
                <p>&nbsp;</p>
                <ol start="9">
                    <li><strong>Actividades Prohibidas ; Ejecución de Políticas.</strong></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>Al aceptar estas Condiciones y “Acuerdos” del servicio, el usuario se compromete a NO:</span></p>
                <ol style={{ listStyleType: "upper-alpha" }}>
                    <li><span style={{ fontWeight: "400" }}>Uilizar el servicio para fines distintos al acceso y uso del “Sistema” (A excepción de lo expresamente permitido en el presente documento), </span></li>
                    <li><span style={{ fontWeight: "400" }}>Ccompartir sesiones de inicio con varias personas. El nombre de usuario debe ser utilizado por una sola persona, y crear accesos separados para tantos usuarios considere y necesite, </span><em><span style={{ fontWeight: "400" }}>entendiéndose que el “Usuario” firmante del acuerdo es responsable del uso que de los contenidos pudieran hacer los usuarios secundarios.</span></em><em><span style={{ fontWeight: "400" }}><br /></span></em></li>
                    <li><span style={{ fontWeight: "400" }}>Bloquear anuncios, si usted es un “Usuario” con una cuenta gratuita;</span><span style={{ fontWeight: "400" }}><br /></span></li>
                    <li><span style={{ fontWeight: "400" }}>Hacerse pasar por otra persona o entidad, afirmar falsamente una afiliación con cualquier persona, &nbsp;entidad o compañía, o a acceder a “Buscar” “Contenidos” del sistema de otros sin autorización, falsificar la firma o la identidad digital de otra persona, falsificar el origen, la identidad, o el contenido de la información transmitida, o realizar cualquier otra actividad fraudulenta similar;</span><span style={{ fontWeight: "400" }}><br /></span></li>
                    <li><span style={{ fontWeight: "400" }}>Hacer ofertas no solicitadas, anuncios, propuestas, o enviar correo basura o spam a otros usuarios que acceden al sistema. Esto incluye,pero no es limitado a, publicidad no solicitada, materiales promocionales, u otro material solicitado , envío masivo de publicidad comercial, correo principal, anuncios informativos, solicitudes de caridad, y solicitudes de firmas;</span><span style={{ fontWeight: "400" }}><br /></span></li>
                    <li><span style={{ fontWeight: "400" }}>Ingresar al sistema para utilizarlo con propósitos ilegal o en violación de cualquier ley local, estatal, nacional o internacional, incluyendo, y no limitativo, las leyes que rigen la propiedad intelectual y otros derechos de propiedad, así como la protección de datos y privacidad;</span></li>
                    <li><span style={{ fontWeight: "400" }}>Difamar, acosar, abusar, amenazar o defraudar a los usuarios que ingresen al sistema, o recoger, o de procurar recoger, información personal sobre los mismos usuarios o terceros sin su consentimiento;</span><span style={{ fontWeight: "400" }}><br /></span></li>
                    <li><span style={{ fontWeight: "400" }}>Ingresar y/o utilizar el &nbsp;&nbsp;“Sistema” si no es legalmente competente para hacerlo;</span><span style={{ fontWeight: "400" }}><br /></span></li>
                    <li><span style={{ fontWeight: "400" }}>Eliminar,alterar, deshabilitar, dañar o interferir con las funciones relacionadas con la seguridad y comprobación del acceso al “Sistema” para cada usuario, actividades que impidan o limiten el uso o copia de cualquier contenido y su acceso &nbsp;a través del ingreso del sistema, o actividades que impongan y limiten &nbsp;el uso de la verificación y acceso al mismo “Sistema”;</span><span style={{ fontWeight: "400" }}><br /></span></li>
                    <li><span style={{ fontWeight: "400" }}>Realizar ingeniería inversa, descompilar, desensamblar o intentar descubrir el código fuente de comprobación del sistema o cualquier parte del mismo, excepto y únicamente en la medida en que dicha actividad esté expresamente permitida por la ley aplicable;</span></li>
                    <li><span style={{ fontWeight: "400" }}>Modificar, adaptar, traducir o crear trabajos derivados o basados en el “Sistema”, de cualquier parte o módulo del mismo, excepto y únicamente en la medida en que dicha actividad esté expresamente permitida por la legislación aplicable;</span></li>
                    <li><span style={{ fontWeight: "400" }}>Interferir intencionalm</span><em><span style={{ fontWeight: "400" }}>ente o dañar operación d</span></em><span style={{ fontWeight: "400" }}>e acceso al sistema o el disfrute de los usuarios del mismo, por cualquier medio, incluyendo la carga o de otro modo la difusión de virus, adware, spyware, gusanos u otros códigos maliciosos;</span></li>
                    <li><span style={{ fontWeight: "400" }}>Utilizar cualquier, robot, spider, o cualquier otro medio automático para acceder a el sistema sin importar el &nbsp;propósito. Ante esas situaciones y cualquier otras DSL Solutions, Inc. puede utilizar medidas para prevenir o restringir el acceso el sistema;</span></li>
                    <li><span style={{ fontWeight: "400" }}>Interferir o interrumpir el acceso al sistema o los servidores o redes conectadas &nbsp;del “Sistema”, o incumplir los requisitos, procedimientos, políticas o regulaciones de las redes conectadas a la comprobación para el acceso del “Sistema”.</span></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>DSL Solutions Inc. se reserva el derecho a</span><em><span style={{ fontWeight: "400" }}> revisar y modificar con la frecuencia que considere pertinente todo </span></em><span style={{ fontWeight: "400" }}>el “Contenido” para asegurar el cumplimiento de este “Acuerdo” de servicio. En el caso de que DSL Solutions Inc. determine, a su sola discreción, que el uso de comprobación y acceso &nbsp;al sistema se encuentra en violación de estos “Acuerdos” de servicio, DSL Solutions Inc. tendrá el derecho, sin recurso por parte del “Usuario”, de terminar y cerrar &nbsp;inmediatamente la cuenta.</span><br /><br /></p>
                <ol start="10">
                    <li><strong> La cuenta , los pagos , los reembolsos , las actualizaciones y cancelaciones.</strong></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>En cada ingreso al sistema, se le pedirá al usuario que cree una cuenta o varias cuentas dependiendo sus necesidades, &nbsp;establezca &nbsp;sus contraseñas y las &nbsp;modifique a su conveniencia. El usuario &nbsp;es el único responsable de mantener la confidencialidad de su cuenta y contraseña y de restringir el acceso a su ordenador y/o cuenta, aceptando la responsabilidad de todas las actividades que ocurran bajo dichas cuentas con sus contraseñas. Como usuario acepta que la información que proporcione a DLS Solutions, Inc. en el registro y en cualquier otro momento será real, precisa, actualizada y completa. También acepta que se asegurará de que esta información se mantendrá &nbsp;actualizada en todo momento. Si usted tiene razones para creer que su cuenta ya no es segura (por ejemplo, en el caso de pérdida, robo o divulgación o uso de su ID de cuenta y/o contraseña), debe &nbsp;comprometerse a notificar inmediatamente a DSL Solutions, Inc.por escrito </span><em><span style={{ fontWeight: "400" }}>y a la dirección electrónica provista al final de este contrato</span></em><span style={{ fontWeight: "400" }}> ya que puede ser responsable por las pérdidas sufridas por DSL Solutions, Inc. o de sus filiales debido al uso no autorizado de la misma cuenta.</span></p>
                <p><span style={{ fontWeight: "400" }}>A) El usuario realizará durante los primeros cinco (5) días de cada mes &nbsp;el pago acordado con DSL Solutions Inc., a través de:</span></p>
                <ul>
                    <li style={{ fontWeight: "400" }}><span style={{ fontWeight: "400" }}>una &nbsp;tarjeta de crédito válida para todas las cuentas pactadas con DSL Solutions Inc., autorizando a DSL Solutions Inc., a hacer el retiro mensual que los firmantes acuerden, y cuyo monto será comprobable por medio del correo electrónico anexo al final de este contrato.</span></li>
                    <li style={{ fontWeight: "400" }}><span style={{ fontWeight: "400" }}>el envío por parte del usuario a DSL Solutions Inc., de un cheque dentro de &nbsp;primeros </span><strong>10 días del mes,</strong></li>
                    <li style={{ fontWeight: "400" }}><span style={{ fontWeight: "400" }}>el pago en efectivo directo a nuestra cuenta bancaria, misma que se muestra &nbsp;en las facturas mostradas en su módulo administrativo.</span></li>
                </ul>
                <p><span style={{ fontWeight: "400" }}>B) Si el usuario se registra para una cuenta de prueba (10 días sin cargo) &nbsp;y la cual incluye un acceso &nbsp;gratuito, y el usuario decide &nbsp;no cancelar dicha cuenta en el período de prueba especificado (10 días),a partir de esa fecha y hora se le facturará mensualmente por el mismo cargo acordado en el correo electrónico. mencionado previamente (Anexo 1)</span></p>
                <p><em><span style={{ fontWeight: "400" }}> Para cancelar la cuenta, el usuario deberá enviar un correo electrónico a DSL Solutions Inc., &nbsp;en idioma ingles o Espanol, especificando que solicita la suspensión &nbsp;&nbsp;del servicio a partir del momento de enviar dicho correo.</span></em><span style={{ fontWeight: "400" }}> Tenga en cuenta que los 10 "días"</span> <span style={{ fontWeight: "400" }}>de la versión de prueba corresponden a períodos de 24 horas que comienza en la fecha y hora en que se inscribe. Si cancela antes de la tramitación de su primera factura, durante su período de prueba gratuito, no se le cobrará; para realizar lo anterior solo tiene que enviar un correo electrónico y nosotros mismos cancelaremos la cuenta.</span></p>
                <p><span style={{ fontWeight: "400" }}>C) El servicio se cobra una vez transcurrido los 30 días, &nbsp;sobre una base mensual, si requiere realizar el pago anual usted reconoce que dicho pago deberá ser por adelantado y no es reembolsable. No habrá reembolsos o créditos por meses parciales de servicio, reembolsos por actualizaciones / disminuciones, o reembolsos por meses no utilizados en una cuenta abierta. Con el fin de tratar a todos por igual, no se harán excepciones;</span></p>
                <p><span style={{ fontWeight: "400" }}><br /></span><span style={{ fontWeight: "400" }}>D) Las tarifas no incluyen todos los impuestos, gravámenes u obligaciones impuestas por las autoridades fiscales, y usted será responsable del pago de todos los impuestos, gravámenes o derechos a que le corresponda el servicio utilizado;</span></p>
                <p><span style={{ fontWeight: "400" }}>E) El usuario acepta que si decidiese cambiar el tipo de servicio contratado por uno de menor capacidad, esto puede causar la pérdida de “Contenido” , características o capacidades en su “Cuenta” . &nbsp;DSL Solutions no acepta ninguna responsabilidad por tal pérdida, si requiere su “Contenido” antes de modificar la cuenta deberá informar a DSL Solutions Inc, para que éste pueda a su vez colocar dicho “Contenido” en un formato </span><strong>electrónico</strong><span style={{ fontWeight: "400" }}> a selección del “Usuario”; Dentro de los formatos que se compromete DSL Solutions Inc., a entregar al “Usuario” el “Contenido” están:</span></p>
                <ul>
                    <li style={{ fontWeight: "400" }}><span style={{ fontWeight: "400" }}>-Formato en excel (.xlsx)</span></li>
                    <li style={{ fontWeight: "400" }}><span style={{ fontWeight: "400" }}>-Formato PDF</span></li>
                    <li style={{ fontWeight: "400" }}><span style={{ fontWeight: "400" }}>-Formato CSV</span></li>
                </ul>
                <ol start="11">
                    <li><strong> Indemnizaciones a usuarios</strong></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>El usuario acepta defender y mantener en buena fé &nbsp;los &nbsp;términos y la relación con DSL Solutions Inc., con sus compañías filiales, sus sucursales, sus administrativos, empleados y agentes contra demandas, daños, reclamo de daños y gastos incluyendo (y no limitativo) honorarios de abogados, equipos de cómputo, entre otros que pueda sufrir por el ( a) el uso de la página web y su acceso al sistema , (b) el incumplimiento , presunto incumplimiento o violación de las anteriores garantías, representaciones y pactos ,(c) cualquier violación de cualquier derecho de terceros derivada de un “Contenido” del “Usuario” enviado por él u otro “Usuario”, (d) cualquier afirmación de que cualquier “Contenido” del usuario enviado por él u otro &nbsp;usuario que haya causado daños a un tercero, (e) cualquier alegación o reclamación &nbsp;del uso &nbsp;del “Sistema” por los “Usuarios” que constituya una violación moral en una jurisdicción, o (f) cualquier otra violación de estos “Acuerdos” de servicio. La obligación del “Usuario” &nbsp;es la de defender &nbsp;y mantener en buenos términos &nbsp;con DSL Solutions Inc., ya que el “Sistema” está diseñado a la medida y necesidades específicas del mismo “Usuario” lo que hace al “Sistema” como un simple gestor del “Contenido”</span></p>
                <ol start="12">
                    <li><strong>Reclamo de garantías</strong></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>El uso y acceso al “Sistema” será bajo riesgo exclusivo del “Usuario”. En la medida &nbsp;que lo permita la ley, DSL Solutions, Inc. , sus filiales , directores , empleados , agentes &nbsp;renuncian a toda garantía , expresa o implícita , en relación con el acceso al sistema y el uso de su “Contenido” . &nbsp;DSL Solutions , Inc. no asume &nbsp;responsabilidad por cualquier (i) &nbsp;errores o imprecisiones del “Contenido” del sitio web y el “Sistema” , ( ii ) lesiones personales o daños , de cualquier naturaleza, que surjan por el acceso y uso &nbsp;del sistema , ( iii ) cualquier error , virus, troyanos, o similares, que pueden ser transmitidas a través del sitio web &nbsp;una vez accediendo al “Sistema” por parte de terceros , y / o ( iv ) cualquier error u omisión en cualquier “Contenido” o por cualquier pérdida o daño de cualquier tipo incurridos como resultado del uso de cualquier “Contenido” publicado , enviado por correo electrónico , transmitido o puesto a disposición a través del acceso &nbsp;al “Sistema”.</span></p>
                <p><span style={{ fontWeight: "400" }}>DSL Solutions Inc., </span><span style={{ fontWeight: "400" }}>no garantiza , respaldar , ser aval, o asumir la responsabilidad de cualquier producto o servicio anunciado u ofrecido por un tercero a través del acceso &nbsp;al “Sistema” o cualquier sitio web enlazado que participe en cualquier banner o otro tipo de publicidad. &nbsp;DSL Solutions, Inc. no será parte ni de ninguna manera será responsable de supervisar cualquier transacción entre un “Usuario”, sus clientes y de &nbsp;proveedores de productos o servicios en el mismo “Sistema”, solo para el caso en que lo mencione de forma escrita y lo acuerde antes con el “Usuario”.</span></p>
                <ol start="13">
                    <li><strong> Limitaciones y responsabilidades</strong></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>El Usuario acepta no responsabilizar a DSL Solutions Inc., a sus filiales, directores , empleados o agentes por pérdidas o daños, ya sean directos, indirectos, incidentales , especiales , punitivos o consecuentes , que se incurra como resultado del uso del “Usuario” al acceder al “Sistema”, (ii) errores o inexactitudes del “Contenido”, ( ii ) lesiones personales o daños de cualquier tipo que sean, como consecuencia del acceso del “Usuario” al “Sistema, ( iii ) cualquier interrupción o cese de la transmisión hacia o desde el &nbsp;“Sistema” , ( iv ) cualquier error, virus , caballos de Troya , o similares , que pueden ser transmitidos a través del acceso del “Sistema” por parte de terceros , y/o (v) cualquier error u omisión en cualquier “Contenido” o por cualquier pérdida o daño de cualquier tipo incurridos como resultado del uso del “Usuario” de cualquier “Contenido” publicado, enviado por correo electrónico, transmitido o puesto a disposición a través del acceso del sistema.</span></p>
                <p><span style={{ fontWeight: "400" }}>Ciertas jurisdicciones no permiten limitaciones en garantías implícitas o la exclusión o limitación de ciertos daños . Si usted reside es tal jurisdicción , algunas o todas las anteriores renuncias, exclusiones o limitaciones pueden no aplicarse a usted, y &nbsp;puede tener derechos adicionales . Las limitaciones o exclusiones de garantías, recursos o responsabilidades contenidas en estas condiciones de servicio se le aplicarán en la mayor medida que se permitan las limitaciones o exclusiones con arreglo a las leyes de la jurisdicción en la que se encuentra.</span></p>
                <ol start="14">
                    <li><strong> Terminación</strong></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>El “Usuario” puede cancelar la utilización del servicios y/o cancelar su “Cuenta” con o sin causa en cualquier momento mediante notificación a DSL Solutions, Inc vía correo electrónico y en cualquier momento que lo decida; sin embargo, &nbsp;una cuenta cancelada puede seguir existiendo durante un período razonable de tiempo. El “Usuario” puede dar por terminada su cuenta sólo en la forma establecida en esta sección 14 (suspensión del servicio y/o cancelación de la cuenta, pero notificando a DSL Solutions, Inc.). Adicionalmente y tal como se especifica en el apartado 9, DSL Solutions Inc. tiene el </span><span style={{ fontWeight: "400" }}>&nbsp;derecho a cancelar la “Cuenta” y su acceso al sistema en la manera que se viole este “Acuerdo” de servicio. </span></p>
                <ol start="15">
                    <li><strong> Misceláneos</strong></li>
                </ol>
                <p><span style={{ fontWeight: "400" }}>A) Estas condiciones del “Acuerdo” de servicio se regirán e interpretarán en conformidad con las leyes del estado de Minnesota , a excepción de sus conflictos principales legales. El “Usuario” está de acuerdo que la jurisdicción y lugar será en los tribunales estatales y federales en la ciudad de Minneapolis , Minnesota USA.</span></p>
                <p><span style={{ fontWeight: "400" }}>B) DSL Solutions Inc., puede transferir y ceder estos “Acuerdos” de servicio &nbsp;sin restricción alguna. El “Usuario” no podrá transferir ni ceder ninguno de estos Términos de Servicio .</span></p>
                <p><span style={{ fontWeight: "400" }}>C) El “Usuario” afirma y garantiza que es legalmente competente para entrar en estas condiciones, obligaciones , afirmaciones, declaraciones , pactos y garantías establecidos en este “Acuerdo” .</span></p>
                <p><span style={{ fontWeight: "400" }}>D ) Si alguna disposición de este “Acuerdo” de servicio es encontrado como ilegal o no ejecutable , se hará cumplir en la medida máxima permitida , así como la legalidad y aplicabilidad de las restantes disposiciones de este “Acuerdo” de servicio no se verán afectada.</span></p>
                <p><span style={{ fontWeight: "400" }}>E ) DSL Solutions,Inc. puede proporcionarle avisos, incluidos los relativos a cambios en este “Acuerdo” de servicio, por correo electrónico, correo postal o mediante su publicación al acceder al sistema. La notificación se considerará como enterada y aplicada veinticuatro horas después del envío de correo electrónico &nbsp;o al acceso del sistema, para el caso de ser una notificación vía correo postal, se considerará su aplicación 3 días después del envío.</span><strong><br /><br /></strong></p>
                <p><strong>Requisitos del sistema:</strong></p>
                <p><span style={{ fontWeight: "400" }}>Las dos últimas versiones de Firefox &nbsp;( Windows y Mac )</span><span style={{ fontWeight: "400" }}><br /></span><span style={{ fontWeight: "400" }}>La versión actual de Google Chrome ( Windows y Mac )</span><span style={{ fontWeight: "400" }}><br /></span><span style={{ fontWeight: "400" }}>El sistema requiere que &nbsp;&nbsp;cookies y JavaScript estén activados con el fin de funcionar correctamente .</span><span style={{ fontWeight: "400" }}><br /></span></p>
                <p><strong>El servicio es ofrecido por soluciones DSL , Inc., con oficinas ubicadas en:</strong></p>
                <ul>
                    <li><span style={{ fontWeight: "400" }}>-2400 Central Ave Ne &nbsp;Minneapolis, MN 55418 (612) 781- 9077</span></li>
                    <li><span style={{ fontWeight: "400" }}>-Calle Galeana no 65 Colonia Centro Axochiapan Morelos México CP 62950 + 52 (735) 542 9882</span></li>
                    <li><span style={{ fontWeight: "400" }}>-Correo: </span><a href="mailto:dslcorporativo@gmail.com"><span style={{ fontWeight: "400" }}>dslcorporativo@gmail.com</span></a></li>
                    <li><span style={{ fontWeight: "400" }}>-Correo: </span><a href="mailto:dslsoportetecnico@gmail.com"><span style={{ fontWeight: "400" }}>dslsoportetecnico@gmail.com</span></a></li>
                    <li><span style={{ fontWeight: "400" }}>-Correo: </span><a href="mailto:dslcontabilidad@gmail.com"><span style={{ fontWeight: "400" }}>dslcontabilidad@gmail.com</span></a></li>
                </ul>
            </div>
        </section>
    );
}

export default TerminosYPoliticas;